"""Add employee fields to Worker

Revision ID: 2408f5a18520
Revises: None
Create Date: 2026-06-24 11:34:01.289981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2408f5a18520'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('role', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('joining_date', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('shift_start', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('shift_end', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'shift_end')
    op.drop_column('workers', 'shift_start')
    op.drop_column('workers', 'profile_photo_url')
    op.drop_column('workers', 'joining_date')
    op.drop_column('workers', 'role')
    op.drop_column('workers', 'designation')
    op.drop_column('workers', 'mobile_number')
    # ### end Alembic commands ###
